language: objective-c
osx_image: xcode8.1

install:
  - bundle install
  - pod repo update > /dev/null
  - ./install.sh

script:
  - set -o pipefail && xcodebuild -workspace Antidote.xcworkspace -scheme Antidote build | xcpretty

